from pydantic import BaseModel, Field, field_validator


class RAGQueryRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="The question to query the RAG model",
    )

    @field_validator("question")
    @classmethod
    def question_must_not_be_blank(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("question must not be blank")
        return value

class RAGQueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the RAG model")
    citations: list["RAGCitation"] = Field(default_factory=list)


class RAGCitation(BaseModel):
    id: str = Field(..., description="Citation identifier used in the answer, e.g. S1")
    chunk_id: str
    filename: str
    url: str | None = None
    page: int
    page_label: str | None = None
    total_pages: int | None = None
    start_index: int
    end_index: int
    text: str
