"""Multi-query retrieval over the existing pgvector table."""

import os
from collections.abc import Sequence
from typing import Protocol

from langchain_core.documents import Document
from langchain_core.load import dumps
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableLambda
from langchain_groq import ChatGroq
from langchain_postgres import PGEngine, PGVectorStore
from langsmith import traceable
from sqlalchemy import select

from app.configs.prompts import MULTI_QUERY_PROMPT
from app.db import _database_url, session_scope
from app.models.document import Document as SourceDocument
from app.services.langchain_indexer import (
    DEFAULT_EMBEDDING_MODEL,
    VECTOR_SCHEMA,
    VECTOR_TABLE,
    close_pg_engine,
    make_embedding_service,
)

DEFAULT_COLLECTION = os.getenv("VECTOR_COLLECTION", "digemid")
DEFAULT_QUERY_COUNT = 5
DEFAULT_RESULTS_PER_QUERY = 4
MAX_QUERY_COUNT = 10


class QueryGenerator(Protocol):
    def invoke(self, values: dict[str, object]) -> list[str]: ...


class DocumentRetriever(Protocol):
    def batch(self, queries: list[str]) -> list[list[Document]]: ...


def parse_queries(output: str) -> list[str]:
    """Return distinct non-empty query lines generated by the model."""
    return list(dict.fromkeys(line.strip() for line in output.splitlines() if line.strip()))


def make_query_generator() -> QueryGenerator:
    model = ChatGroq(
        model=os.getenv("MULTI_QUERY_MODEL", "llama-3.3-70b-versatile"),
        temperature=0,
        max_tokens=256,
    )
    return MULTI_QUERY_PROMPT | model | StrOutputParser() | RunnableLambda(parse_queries)


def get_unique_union(documents: Sequence[Sequence[Document]]) -> list[Document]:
    """Return retrieved documents once, preserving their first retrieval order."""
    unique_documents: dict[str, Document] = {}
    for document_list in documents:
        for document in document_list:
            unique_documents.setdefault(dumps(document), document)
    return list(unique_documents.values())


def attach_source_metadata(documents: list[Document], collection: str) -> list[Document]:
    """Attach stable document metadata needed to render citations."""
    doc_hashes = {
        document.metadata.get("doc_hash")
        for document in documents
        if document.metadata.get("doc_hash")
    }
    if not doc_hashes:
        return documents

    with session_scope() as session:
        sources = session.scalars(
            select(SourceDocument).where(
                SourceDocument.collection == collection,
                SourceDocument.doc_hash.in_(doc_hashes),
            )
        ).all()
    source_by_hash = {source.doc_hash: source for source in sources}

    for document in documents:
        source = source_by_hash.get(document.metadata.get("doc_hash"))
        if source is None:
            continue
        start_index = int(document.metadata.get("start_index", 0))
        document.metadata.update(
            {
                "filename": source.filename,
                "source_url": source.source_url,
                "storage_key": source.storage_key,
                "end_index": start_index + len(document.page_content),
            }
        )
    return documents


def retrieve_multiquery_documents(
    question: str,
    retriever: DocumentRetriever,
    query_generator: QueryGenerator,
    *,
    query_count: int = DEFAULT_QUERY_COUNT,
) -> list[Document]:
    """Retrieve matches for the original question and its generated alternatives."""
    if not 1 <= query_count <= MAX_QUERY_COUNT:
        raise ValueError(f"query_count must be between 1 and {MAX_QUERY_COUNT}")

    alternatives = query_generator.invoke(
        {"question": question, "query_count": query_count}
    )
    queries = list(dict.fromkeys([question, *alternatives[:query_count]]))
    return get_unique_union(retriever.batch(queries))


@traceable(name="multi-query-retrieval", run_type="retriever")
async def retrieve_from_pgvector(
    question: str,
    *,
    collection: str = DEFAULT_COLLECTION,
    query_count: int = DEFAULT_QUERY_COUNT,
    results_per_query: int = DEFAULT_RESULTS_PER_QUERY,
) -> list[Document]:
    """Use pgvector similarity search for the original and generated queries."""
    if results_per_query < 1:
        raise ValueError("results_per_query must be positive")

    engine = PGEngine.from_connection_string(
        url=_database_url(),
        pool_size=1,
        max_overflow=0,
    )
    try:
        vectorstore = PGVectorStore.create_sync(
            engine=engine,
            embedding_service=make_embedding_service(
                os.getenv("EMBEDDING_MODEL", DEFAULT_EMBEDDING_MODEL)
            ),
            table_name=VECTOR_TABLE,
            schema_name=VECTOR_SCHEMA,
            metadata_columns=["collection", "doc_hash", "page", "start_index"],
        )
        retriever = vectorstore.as_retriever(
            search_type="similarity",
            search_kwargs={
                "k": results_per_query,
                "filter": {"collection": collection},
            },
        )
        documents = retrieve_multiquery_documents(
            question, retriever, make_query_generator(), query_count=query_count
        )
        return attach_source_metadata(documents, collection)
    finally:
        await close_pg_engine(engine)
